IBMiMake
change to use evfevent as file extension
=> change to use evfevent as file extension

Makefile, makei, mk/def_rules.mk, mk/extractAndLaunch, mk/extractPseudoSrc, mk/footer.mk, mk/header.mk
1. Support IBMiEnvCmdList
2. Support running pseudoCode directly
3. Support running SQL Statement
4. Fixed the problem that make keeps rebuilding
5. Add support for more types including DTAs SQLs BNDDs MSGs
6. Make the Rules.mk more compact since we don't specify the path in the target
=> Finished new BOB

mk/def_rules.mk
=> Support PGM.CLLE, include DBGVIEW for bnd rpg

launch
In the PR, joblog.json will keep track of the field such as
From program . . . . . . . . . : QCADRV2
From library . . . . . . . . : QSYS
Instruction . . . . . . . . : 0544
To program . . . . . . . . . . : QP0LCWRL
To library . . . . . . . . . : QSYS
To module . . . . . . . . . : QP0LCWRL
To procedure . . . . . . . . : main
To statement . . . . . . . . : 66
=> Joblog.json tracks more information

mk/def_rules.mk
Add curlib, preusrlibl, postusrlibl to VPATH
=> extend VPATH

mk/def_rules.mk
=> add incdir to VPATH

docs/cli/makei.md, scripts/makei
=> Do not generate .ibmi.json target ccsid when invoking makei cvtsrcpf

docs/getting-started/sample-build.md
Namely, remove need for 5250 emulator
=> Simplify sample project steps

makei/init_project.py
=> typo fix for bare template

makei/build.py
=> Fix path to make

docs/index.html
=> update docsify-plugin-toc to 1.3.1

scripts/launch
=> Fix fail to add multiple preUsrLibl/postUsrLibl

mk/Makefile
=> Fix unable to enable CompatibilityMode

.vscode/launch.json, mk/def_rules.mk
add launch.json to show how to debug the base python from vscode
=> add ability to debug from vs code

mk/def_rules.mk
=> Use CRTCBLPGM instead of CRTPRTF

scripts/makei
Signed-off-by: edmundreinhardt <edmund.reinhardt@ca.ibm.com>
=> improve description of ccsid parm of cvtsrcpf

docs/welcome/features.md
Signed-off-by: edmundreinhardt <edmund.reinhardt@ca.ibm.com>
=> Document BNDDIRSRC file extenstion

bob.spec, docs/contributing/build-rpm.md
Document steps in building BOB
=> improve build docs

bob.spec, docs/contributing/build-rpm.md, docs/getting-started/prerequisites.md, docs/prepare-the-project/create-a-new-project.md, docs/prepare-the-project/iproj-json.md, makei/const.py
Signed-off-by: John Bampton <jbampton@gmail.com>
=> Fix spelling

bin/crtfrmstmf, bin/makei
=> remove the check for jq

src/mk/def_rules.mk
did not pick up the directory specific values
The values were generated correction into the /tmp include
but are not picked up within the Makefile
=> The OBJPATH, OBJLIB and TGTCCSID was not properly initialized based on .ibmi.json

CHANGELOG, bin/crtfrmstmf, bin/makei, src/scripts/checkIfBuilt, src/scripts/crtfrmstmf, src/scripts/getJobLog
This PR may be more cosmetic than anything, but I have a suspicion that it might have an impact on some issues, like this one:
https://github.com/IBM/ibmi-bob/issues/271
=> Use bash shebang

CHANGELOG, src/makei/cvtsrcpf.py, src/makei/ibmi_json.py, src/mk/def_rules.mk
This variable was resolved too early and ended up blank
=> Fix TGTCCSID resolving

docs/welcome/features.md, src/scripts/extractAndLaunch
Pseudo source consists of multiple CL commands in a stream file.
When
=> If any subcommand of pseudo source fails - exit with error

docs/prepare-the-project/create-a-new-project.md
=> correct link to rules.mk.md
